input UserInput {
    "Identificado del usuario"
    id: ID
    "Nombre del usuario"

    name: String!
    "Si es instructor"

    instructor: Boolean!
    twitter: String

    "Pagina web personal"
    web: String
}